name: Terratest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          cd test
          go mod tidy

      - name: Run Terratest
        run: |
          cd test
          go test -v